// ============================================================
// @pgos/cli — Context Command
// Compile, export, and run next-generation AI-POS intelligence
// ============================================================

import type { Command } from 'commander';
import chalk from 'chalk';
import ora from 'ora';
import { join, resolve } from 'path';
import { writeFile, mkdir, readFile } from 'fs/promises';
import { formatTokens, VERSION } from '@pgos/core';
import { compileContext, packageContext } from '@pgos/context-engine';

export function registerContextCommand(program: Command): void {
  const ctx = program
    .command('context')
    .description('Manage project context');

  ctx
    .command('compile')
    .description('Compile project context')
    .argument('[path]', 'Project root path', '.')
    .option('-l, --levels <levels>', 'Context levels (comma-separated)', 'L0,L1,L2,L3,L4,L5,L6')
    .action(async (projectPath: string, options: { levels: string }) => {
      const rootPath = resolve(process.cwd(), projectPath);
      const levels = options.levels.split(',') as ('L0' | 'L1' | 'L2' | 'L3' | 'L4' | 'L5' | 'L6')[];
      const spinner = ora('Compiling next-gen context...').start();

      try {
        const result = await compileContext('cli-project', rootPath, { levels });

        spinner.succeed(chalk.green('Context compiled successfully with dynamic AI-POS intelligence!'));
        console.log('');
        console.log(`  ${chalk.dim('Files processed:')} ${chalk.white(String(result.filesProcessed))}`);
        console.log(`  ${chalk.dim('Total tokens:')}    ${chalk.yellow(formatTokens(result.totalTokens))}`);
        console.log(`  ${chalk.dim('Optimized:')}       ${chalk.green(formatTokens(result.optimizedTokens))}`);
        console.log(`  ${chalk.dim('Reduction:')}       ${chalk.cyan(`${result.reductionPercent}%`)}`);
        console.log(`  ${chalk.dim('Duration:')}        ${chalk.white(`${result.duration}ms`)}`);

        // Fetch L0 package for backward-compat display/sync
        const l0Pkg = result.packages.get('L0');
        const intel = l0Pkg?.content;

        if (intel) {
          const confidence = intel.validationIntelligence?.confidenceScore ?? 85;
          const statusChalk = confidence >= 90 ? chalk.green : confidence >= 70 ? chalk.yellow : chalk.red;
          console.log(`  ${chalk.dim('Confidence Score:')} ${statusChalk(`${confidence}%`)}`);
          console.log(`  ${chalk.dim('Output Directory:')} ${chalk.cyan('.guardian/ai-pos/')}`);
        }

        // ─── PERSIST ENRICHED OUTPUTS TO .guardian/ ───────────────
        const timestamp = new Date().toISOString();

        try {
          const contextDir = join(rootPath, '.guardian', 'context');
          const knowledgeDir = join(rootPath, '.guardian', 'knowledge');
          const memoryDir = join(rootPath, '.guardian', 'memory');
          const telemetryDir = join(rootPath, '.guardian', 'telemetry');

          await mkdir(contextDir, { recursive: true });
          await mkdir(knowledgeDir, { recursive: true });
          await mkdir(memoryDir, { recursive: true });
          await mkdir(telemetryDir, { recursive: true });

          // 1. Context summary with verifiable stats
          const contextSummary = {
            pgosVersion: VERSION,
            generatedAt: timestamp,
            rootPath,
            filesProcessed: result.filesProcessed,
            totalTokens: result.totalTokens,
            optimizedTokens: result.optimizedTokens,
            reductionPercent: result.reductionPercent,
            durationMs: result.duration,
            levelsCompiled: levels,
          };
          await writeFile(join(contextDir, 'context-summary.json'), JSON.stringify(contextSummary, null, 2));

          // 2. Generate Mermaid dependency graph from codebase_graph.json
          try {
            const graphRaw = await readFile(join(contextDir, 'codebase_graph.json'), 'utf-8');
            const graph = JSON.parse(graphRaw);

            let mermaid = 'graph LR\n';
            mermaid += '  %% Auto-generated by PGOS Context Engine\n';
            mermaid += `  %% Generated: ${timestamp}\n`;
            mermaid += `  %% Files: ${result.filesProcessed} | Tokens: ${result.totalTokens}\n\n`;

            const moduleNodes = (graph.nodes || []).filter((n: any) => n.type === 'module');
            const fileNodes = (graph.nodes || []).filter((n: any) => n.type === 'file');
            const classNodes = (graph.nodes || []).filter((n: any) => n.type === 'class');
            const funcNodes = (graph.nodes || []).filter((n: any) => n.type === 'function');
            const importEdges = (graph.edges || []).filter((e: any) => e.type === 'import');
            const containsEdges = (graph.edges || []).filter((e: any) => e.type === 'contains');

            mermaid += '  classDef moduleStyle fill:#2d3748,stroke:#4fd1c5,stroke-width:2px,color:#e2e8f0\n';
            mermaid += '  classDef fileStyle fill:#1a202c,stroke:#63b3ed,stroke-width:1px,color:#bee3f8\n';
            mermaid += '  classDef classStyle fill:#2a4365,stroke:#f6ad55,stroke-width:1px,color:#fefcbf\n';
            mermaid += '  classDef funcStyle fill:#1a365d,stroke:#9ae6b4,stroke-width:1px,color:#c6f6d5\n\n';

            const fileToModule = new Map<string, string>();
            for (const edge of containsEdges) {
              if (edge.source.startsWith('module::')) {
                fileToModule.set(edge.target, edge.source.replace('module::', ''));
              }
            }

            const moduleFiles = new Map<string, any[]>();
            for (const file of fileNodes) {
              const mod = fileToModule.get(file.id) || 'root';
              if (!moduleFiles.has(mod)) moduleFiles.set(mod, []);
              moduleFiles.get(mod)!.push(file);
            }

            const moduleEntries = Array.from(moduleFiles.entries()).slice(0, 10);
            for (const [modName, files] of moduleEntries) {
              const safeModName = modName.replace(/[^a-zA-Z0-9_]/g, '_');
              mermaid += `  subgraph ${safeModName}["📁 ${modName}"]\n`;
              for (const file of files.slice(0, 5)) {
                const safeId = file.id.replace(/[^a-zA-Z0-9_]/g, '_');
                mermaid += `    ${safeId}["${file.label} (${file.loc || 0} LOC)"]\n`;
              }
              if (files.length > 5) {
                mermaid += `    ${safeModName}_more["... +${files.length - 5} more files"]\n`;
              }
              mermaid += '  end\n\n';
            }

            for (const edge of importEdges.slice(0, 30)) {
              const src = edge.source.replace(/[^a-zA-Z0-9_]/g, '_');
              const tgt = edge.target.replace(/[^a-zA-Z0-9_]/g, '_');
              if (src && tgt && src !== tgt) {
                mermaid += `  ${src} --> ${tgt}\n`;
              }
            }

            mermaid += `\n  %% Stats: ${moduleNodes.length} modules, ${fileNodes.length} files, ${classNodes.length} classes, ${funcNodes.length} functions\n`;
            mermaid += `  %% Edges: ${importEdges.length} imports, ${containsEdges.length} containment\n`;

            await writeFile(join(contextDir, 'dependency-graph.mermaid'), mermaid);
            console.log(`  ${chalk.dim('Graph:')}          ${chalk.green('.guardian/context/dependency-graph.mermaid')}`);
            
            // Generate HTML viewer for the graph
            const html = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PGOS Dependency Graph</title>
    <style>
        body { margin: 0; padding: 0; background-color: #0f172a; color: #f8fafc; font-family: 'Inter', sans-serif; display: flex; flex-direction: column; height: 100vh; }
        header { padding: 1rem 2rem; border-bottom: 1px solid #334155; background-color: #1e293b; display: flex; justify-content: space-between; align-items: center; }
        h2 { margin: 0; font-size: 1.5rem; }
        .meta { color: #94a3b8; font-size: 0.9rem; }
        .mermaid-container { flex: 1; overflow: auto; padding: 2rem; display: flex; justify-content: center; align-items: flex-start; }
    </style>
</head>
<body>
    <header>
        <div>
            <h2>PGOS Codebase Dependency Graph</h2>
            <div class="meta">Generated: ${timestamp}</div>
        </div>
        <div class="meta" style="text-align: right;">
            <div>Files Processed: <strong style="color: #4fd1c5;">${result.filesProcessed}</strong></div>
            <div>Context Tokens: <strong style="color: #f6ad55;">${result.totalTokens}</strong></div>
        </div>
    </header>
    <div class="mermaid-container">
        <pre class="mermaid">
${mermaid}
        </pre>
    </div>
    <script type="module">
        import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
        mermaid.initialize({ startOnLoad: true, theme: 'dark', securityLevel: 'loose' });
    </script>
</body>
</html>`;
            await writeFile(join(contextDir, 'dependency-graph.html'), html);
            console.log(`  ${chalk.dim('HTML Viewer:')}    ${chalk.green('.guardian/context/dependency-graph.html')}`);
          } catch (e) {
            console.error('Failed to write graph', e);
          }

          // Generate highly optimized LLM Context file for AI vibe coding
          if (intel) {
            const rules = intel.aiEditRules;
            const llmContext = `# PGOS AI Context & Rules
> 🤖 **For AI Assistants:** This file provides a highly compressed, high-fidelity context of the entire project. Use this to understand the architecture, boundaries, and style of the codebase without needing to ingest thousands of files.
> **Vibe Coding Ready:** This document saves roughly ${result.totalTokens - result.optimizedTokens} tokens per prompt.

## 🏗️ Architecture & Layers
- **Pattern**: ${intel.projectIdentity?.framework ? `${intel.projectIdentity.framework} / ` : ''}${intel.architectureIntelligence?.detectedPattern ?? 'Layered'}
${intel.architectureIntelligence?.layers?.map((l: any) => `- **${l.name}**: ${l.components.join(', ')}`).join('\n') || 'Not inferred'}

## 💅 Coding Style & Conventions
- **Indentation**: ${intel.codingStyle?.indentation} (${intel.codingStyle?.indentSize} chars)
- **Naming Convention**: ${intel.codingStyle?.namingConvention}
- **File Organization**: ${intel.codingStyle?.fileOrganization}

## 🔌 Core Dependencies
${intel.dependencies?.slice(0, 15).map((d: any) => `- \`${d.name}\` (${d.type})`).join('\n') || 'None'}

## 🤖 AI OPERATING RULES & SAFETY COMPLIANCE

### ALWAYS
${rules?.always?.map((r: string) => `- ✅ ${r}`).join('\n') || '- Run verification and linting.'}

### NEVER
${rules?.never?.map((r: string) => `- ❌ ${r}`).join('\n') || '- Corrupt lockfiles.'}

### BEFORE EDIT
${rules?.beforeEdit?.map((r: string) => `- 📋 ${r}`).join('\n') || '- Assess edit blast radius.'}

### AFTER EDIT
${rules?.afterEdit?.map((r: string) => `- ✔️ ${r}`).join('\n') || '- Run affected tests.'}

---
*Generated by PGOS Context Engine at ${timestamp} | Original Tokens: ${result.totalTokens} -> Optimized: ${result.optimizedTokens}*
`;
            await writeFile(join(contextDir, 'llm-context.md'), llmContext);
            console.log(`  ${chalk.dim('AI Prompt:')}      ${chalk.magenta('.guardian/context/llm-context.md')}`);

            // Auto-sync to popular AI IDEs for seamless portability
            const syncPaths = ['.cursorrules', '.windsurfrules', '.github/copilot-instructions.md'];
            for (const syncPath of syncPaths) {
              try {
                const targetPath = join(rootPath, syncPath);
                await mkdir(join(targetPath, '..'), { recursive: true });
                await writeFile(targetPath, llmContext);
              } catch {
                // Skip if permission issues
              }
            }
            console.log(`  ${chalk.dim('AI Sync:')}        ${chalk.magenta('Synced to Cursor, Windsurf, & Copilot rules')}`);
          }

          // 3. Knowledge manifest — project summary
          const knowledgeManifest = {
            pgosVersion: VERSION,
            generatedAt: timestamp,
            projectRoot: rootPath,
            projectName: rootPath.split(/[\\/]/).pop() || 'unknown',
            stats: {
              filesProcessed: result.filesProcessed,
              totalTokens: result.totalTokens,
              optimizedTokens: result.optimizedTokens,
              compressionRatio: result.reductionPercent,
            },
            levelsCompiled: levels,
            contextFiles: [
              'context/codebase_graph.json',
              'context/context-summary.json',
              'context/dependency-graph.mermaid',
            ],
          };
          await writeFile(join(knowledgeDir, 'project-manifest.json'), JSON.stringify(knowledgeManifest, null, 2));

          // 4. Memory — append compilation history
          let history: any[] = [];
          try {
            const existing = await readFile(join(memoryDir, 'compilation-history.json'), 'utf-8');
            history = JSON.parse(existing);
          } catch {
            // First run
          }
          history.push({
            compiledAt: timestamp,
            filesProcessed: result.filesProcessed,
            totalTokens: result.totalTokens,
            optimizedTokens: result.optimizedTokens,
            reductionPercent: result.reductionPercent,
            durationMs: result.duration,
          });
          if (history.length > 100) history = history.slice(-100);
          await writeFile(join(memoryDir, 'compilation-history.json'), JSON.stringify(history, null, 2));

          // 5. Telemetry
          const telemetry = {
            pgosVersion: VERSION,
            command: 'context compile',
            executedAt: timestamp,
            durationMs: result.duration,
            filesProcessed: result.filesProcessed,
            totalTokens: result.totalTokens,
            optimizedTokens: result.optimizedTokens,
            reductionPercent: result.reductionPercent,
          };
          await writeFile(join(telemetryDir, `context-${Date.now()}.json`), JSON.stringify(telemetry, null, 2));

          console.log(`  ${chalk.dim('Outputs:')}        ${chalk.green('.guardian/context/, knowledge/, memory/')}`);
        } catch {
          // Don't fail the command if persistence fails
        }

        console.log('');
      } catch (error) {
        spinner.fail(chalk.red('Context compilation failed'));
        console.error(error instanceof Error ? error.message : error);
        process.exit(1);
      }
    });

  // ─── NEW CLI COMMAND: guardian context intelligence ───────────────────
  ctx
    .command('intelligence')
    .description('Run full next-generation AI-POS intelligence and generate all 20+ artifacts')
    .argument('[path]', 'Project root path', '.')
    .action(async (projectPath: string) => {
      const rootPath = resolve(process.cwd(), projectPath);
      const spinner = ora('Generating full AI-POS project intelligence...').start();

      try {
        const result = await compileContext('cli-project', rootPath, {
          levels: ['L0', 'L1', 'L2', 'L3', 'L4', 'L5', 'L6'],
        });

        spinner.succeed(chalk.green('AI-POS Intelligence generation complete! ✨'));
        console.log('');
        
        const l0Pkg = result.packages.get('L0');
        const intel = l0Pkg?.content;

        if (intel) {
          const confidence = intel.validationIntelligence?.confidenceScore ?? 90;
          const statusChalk = confidence >= 90 ? chalk.green.bold : confidence >= 70 ? chalk.yellow.bold : chalk.red.bold;
          
          console.log(chalk.cyan.bold('--- AI-POS INTELLIGENCE OVERVIEW ---'));
          console.log(`  ${chalk.dim('Project Name:')}      ${chalk.white.bold(intel.projectIdentity?.name || 'unknown')}`);
          console.log(`  ${chalk.dim('Framework:')}         ${chalk.white(intel.projectIdentity?.framework || 'None')}`);
          console.log(`  ${chalk.dim('Architecture:')}      ${chalk.white(intel.architectureIntelligence?.detectedPattern || 'layered')}`);
          console.log(`  ${chalk.dim('Confidence Score:')}  ${statusChalk(`${confidence}%`)}`);
          
          // Safety classifications
          const s = intel.safetyClassification;
          console.log(`  ${chalk.dim('Safety Zones:')}      🟢 Safe: ${chalk.green(s?.safeFiles?.length || 0)} | 🟡 Caution: ${chalk.yellow(s?.cautionFiles?.length || 0)} | 🔴 Critical: ${chalk.red(s?.criticalFiles?.length || 0)} | ⛔ DNM: ${chalk.red.bold(s?.doNotModifyZones?.length || 0)}`);
          
          // Technical Debt and Risks
          console.log(`  ${chalk.dim('Risk Level Score:')}  ${chalk.yellow(`${intel.riskIntelligence?.overallRiskScore || 0}/100`)}`);
          console.log(`  ${chalk.dim('Technical Debt:')}    ${chalk.white(`${intel.technicalDebt?.totalCount || 0} items (${intel.technicalDebt?.criticalCount || 0} critical)`)}`);
          
          // Output directory information
          console.log('');
          console.log(chalk.cyan.bold('--- GENERATED AI-POS ARTIFACTS ---'));
          console.log(`  Isolated directory:  ${chalk.green('.guardian/ai-pos/')}`);
          console.log(`  Verifiable Index:    ${chalk.green('.guardian/ai-pos/AI_INDEX.json')}`);
          console.log(`  Master Context Doc:  ${chalk.green('.guardian/ai-pos/AI_CONTEXT.md')}`);
          console.log(`  Architecture Doc:    ${chalk.green('.guardian/ai-pos/AI_ARCHITECTURE.md')}`);
          console.log(`  Execution Lifecycle: ${chalk.green('.guardian/ai-pos/AI_RUNTIME.md')}`);
          console.log(`  Features Inventory:  ${chalk.green('.guardian/ai-pos/AI_FEATURES.md')}`);
          console.log(`  Dependency Graph:    ${chalk.green('.guardian/ai-pos/graphs/AI_DEPENDENCY_GRAPH.json')}`);
          console.log(`  Validation Report:   ${chalk.green('.guardian/ai-pos/AI_VALIDATION.json')}`);
          console.log(`  Active Work State:   ${chalk.green('.guardian/ai-pos/AI_ACTIVE_STATE.md')}`);
          console.log('');
          console.log(`  ${chalk.dim('AI rules synced toCursorRules, WindsurfRules, & GitHub Copilot instructions!')}`);
        }
        console.log('');
      } catch (error) {
        spinner.fail(chalk.red('AI-POS Intelligence generation failed'));
        console.error(error instanceof Error ? error.message : error);
        process.exit(1);
      }
    });

  ctx
    .command('export')
    .description('Export context for AI model')
    .argument('[path]', 'Project root path', '.')
    .option('-m, --model <model>', 'Target model', 'gpt-4')
    .option('-f, --format <format>', 'Output format (yaml|json|markdown|xml)', 'yaml')
    .option('-t, --max-tokens <tokens>', 'Max token budget', '40000')
    .option('-o, --output <file>', 'Output file', 'project_context.yaml')
    .action(async (projectPath: string, options: { model: string; format: string; maxTokens: string; output: string }) => {
      const rootPath = resolve(process.cwd(), projectPath);
      const spinner = ora(`Exporting context for ${options.model}...`).start();

      try {
        const result = await compileContext('cli-project', rootPath, { levels: ['L0', 'L1', 'L2'] });
        const packaged = packageContext(result.packages, {
          targetModel: options.model,
          format: options.format as 'yaml' | 'json' | 'markdown' | 'xml',
          maxTokens: parseInt(options.maxTokens, 10),
        });

        await writeFile(join(rootPath, options.output), packaged.content, 'utf-8');

        spinner.succeed(chalk.green(`Context exported to ${options.output}`));
        console.log('');
        console.log(`  ${chalk.dim('Format:')} ${chalk.white(packaged.format)}`);
        console.log(`  ${chalk.dim('Tokens:')} ${chalk.yellow(formatTokens(packaged.tokens))}`);
        console.log(`  ${chalk.dim('Model:')}  ${chalk.cyan(packaged.modelTarget)}`);
        console.log('');
      } catch (error) {
        spinner.fail(chalk.red('Export failed'));
        console.error(error instanceof Error ? error.message : error);
        process.exit(1);
      }
    });
}
