# AI Context & Operating Rules — app
> **FOR AI AGENTS**: Read `.guardian/ai-pos/AI_REPOSITORY_BRAIN.md` FIRST — it provides 90-98% of the context you need.

## Project Overview
- **Name**: app
- **Stack**: TypeScript / React
- **Architecture**: Monorepo
- **Scale**: 123 files | 18,406 LOC
- **Readiness Score**: 65% [NEEDS REFRACTORING]
- **Health Coverage**: 38% Test Density
- **Confidence**: 90%
- **Brain File**: `.guardian/ai-pos/AI_REPOSITORY_BRAIN.md`

## Safety Zones
- Safe (34): Tests, specs, documentation — low risk
- Caution (54): Business logic, routing — review before changing
- Critical (35): Auth, DB, config, entry points — requires impact analysis

## AI Operating Rules

### ALWAYS
- Read AI_REPOSITORY_BRAIN.md §15 (Blast Radius) before modifying critical files
- Preserve all existing comments, docstrings, and documentation
- Match the project code style and conventions
- Verify all imports resolve correctly
- Use validation check pipelines before pushing to origin

### NEVER
- Never delete test files without writing replacements
- Never hardcode credentials, API keys, or secrets
- Never leave empty stubs, TODO placeholders, or incomplete implementations
- Never modify Critical files without checking blast radius (§15)
- Never bypass lint, build, or test validation pipelines

### BEFORE EDITING
- Check file safety zone in Brain §22
- Review blast radius in §15 for cascading impact analysis
- Review function intelligence in §6 for the target function
- Identify affected tests in §14

### AFTER EDITING
- Validate compilation with zero errors
- Run affected test suites
- Run stub scans to ensure zero placeholders are left
- Regenerate brain if public interfaces changed

---
*Generated by PGOS RIOS v4.0.0 | Read AI_REPOSITORY_BRAIN.md first*
