# AI Context & Operating Rules — app
> **FOR AI AGENTS**: Read `.guardian/ai-pos/AI_REPOSITORY_BRAIN.md` FIRST — it provides 90-98% of the context you need.

## Project Overview
- **Name**: app
- **Stack**: TypeScript / React
- **Architecture**: Monorepo
- **Scale**: 120 files | 17,258 LOC
- **Risk Score**: 23/100
- **Confidence**: 10%
- **Brain File**: `.guardian/ai-pos/AI_REPOSITORY_BRAIN.md`

## Safety Zones
- Safe (33): Tests, specs, documentation — low risk
- Caution (52): Business logic, routing — review before changing
- Critical (35): Auth, DB, config, entry points — requires impact analysis

## AI Operating Rules

### ALWAYS
- Read AI_REPOSITORY_BRAIN.md §15 (Blast Radius) before modifying critical files
- Preserve all existing comments, docstrings, and documentation
- Match the project code style and conventions
- Verify all imports resolve correctly

### NEVER
- Never delete test files without writing replacements
- Never hardcode credentials, API keys, or secrets
- Never leave empty stubs, TODO placeholders, or incomplete implementations
- Never modify Critical files without checking blast radius (§15)

### BEFORE EDITING
- Check file safety zone in Brain §22
- Review blast radius in §15 for cascading impact analysis
- Review function intelligence in §6 for the target function
- Identify affected tests in §14

### AFTER EDITING
- Validate compilation with zero errors
- Run affected test suites
- Regenerate brain if public interfaces changed

---
*Generated by PGOS AIRB v3.0.0 | Read AI_REPOSITORY_BRAIN.md first*
